//se exportan los productos a itemLisContainer

export const products = [
  {
    id: 100,
    nombre: "Armazón",
    category: "armazon",
    marca: "Bless",
    modelo: "Aviador",
    color: "Negro",
    precio: 7500,
    stock: 10,
    img: "https://res.cloudinary.com/dx9cjeuqg/image/upload/v1677609531/aviadorBless_xdcsqv.jpg",
  },
  {
    id: 101,
    nombre: "Lentes de Sol",
    category: "lente",
    marca: "Davor",
    modelo: "Envolvente",
    color: "Negro",
    precio: 7500,
    stock: 10,
    img: "https://res.cloudinary.com/dx9cjeuqg/image/upload/v1677609518/davorHSol_wcfihi.jpg",
  },
  {
    id: 102,
    nombre: "Armazón",
    category: "armazon",
    marca: "Bless",
    modelo: "Hexagonal",
    color: "Dos colores",
    precio: 6500,
    stock: 10,
    img: "https://res.cloudinary.com/dx9cjeuqg/image/upload/v1677609552/hexagonalBless_mgfadq.jpg",
  },
  {
    id: 103,
    nombre: "Armazón",
    category: "armazon",
    marca: "Bless",
    modelo: "Pin Up",
    color: "Dorado y Negro",
    precio: 9000,
    stock: 10,
    img: "https://res.cloudinary.com/dx9cjeuqg/image/upload/v1677609568/pinUp_snhszh.jpg",
  },
  {
    id: 104,
    nombre: "Lentes de Sol",
    category: "lente",
    marca: "Mildura",
    modelo: "Pin Up",
    color: "Dorado y Rosa",
    precio: 10500,
    stock: 10,
    img: "https://res.cloudinary.com/dx9cjeuqg/image/upload/v1677609585/solMildura_ox559u.jpg",
  },
  {
    id: 105,
    nombre: "Lentes de Sol",
    category: "lente",
    marca: "Muzik",
    modelo: "Wayfarer",
    color: "Negro",
    precio: "8500",
    stock: 10,
    img: "https://res.cloudinary.com/dx9cjeuqg/image/upload/v1677609597/solMuzik_pj40s7.jpg",
  },
];
